[build]
  command = "npm run build && cat /etc/os-release && openssl version -v"
  functions = "netlify/functions/"
  publish = "build/"

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 301
